[package]
name = "first-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
chrono = "0.4"
home = "0.5"
anyhow = "1.0"
